services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: eclemens
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: cao
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    container_name: cao_app
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://eclemens:mypassword@72.61.1.14:5432/cao
    depends_on:
      - postgres

volumes:
  postgres_data: